apiVersion: template.openshift.io/v1
kind: Template
message: |
  Created ${NAME} BuildConfig and ImageStream instance

metadata:
  annotations:
    openshift.io/display-name: Bookbag Build
    tags: gpte
    template.openshift.io/bindable: "false"
  name: bookbag-build

parameters:
  - name: NAME
    required: true
    value: bookbag
  - name: BUILDER_IMAGE
    required: true
    value: quay.io/openshifthomeroom/workshop-dashboard:5.0.0
  - name: GIT_REPO
<<<<<<< HEAD
    value: https://github.com/redhat-na-ssa/performance_monitoring_bookbag.git
  - name: GIT_BRANCH
    value: performance-monitoring-new
=======
    value: https://github.com/giofontana/performance_monitoring_bookbag.git
>>>>>>> c967a6d (Init version)

objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: ${NAME}

  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: ${NAME}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:latest
      source:
        git:
          ref: ${GIT_BRANCH}
          uri: ${GIT_REPO}
        type: Git
      strategy:
        sourceStrategy:
          from:
            kind: DockerImage
            name: ${BUILDER_IMAGE}
        type: Source
      triggers: []
